<?php

namespace API\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuisineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuisineRepository extends EntityRepository
{
}
