<?php

namespace API\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocialNetworkRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialNetworkRestaurantRepository extends EntityRepository
{
}
