<?php

namespace API\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeSocialNetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSocialNetworkRepository extends EntityRepository
{
}
